### ISSUE TITLE
cvpyglmnet

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#47]
For cross-validation:
- A new class `cvpyglmnet` will inherit some methods from `pyglmnet` and provide methods for cross-validation, visualization of regularization path, etc.
- This will preserve the R package flavor as much as possible. 
-  Ideally this class just lives in a new script cvpyglmnet.py

**Comment by jasmainak** [comment]
I suppose this can be moved to `0.2` @pavanramkumar ? we should try to get the low-hanging fruits first and ensure that everything works smoothly, tests pass and we the docs / tutorials are great. Especially since `scikit-learn` already offers pretty cross-validation routines, we should have a good reason to replace it + think about the API carefully.

**Comment by pavanramkumar** [comment]
@jasmainak totally agree. my goal is to solve smallest self-contained set of by issues this weekend and focus only on API and documentation issues next week so that we are in time for the milestone `version 0.1`

@hugoguh do you agree?

**Comment by hugoguh** [comment]
I agree with leaving `cvglmnet` for`version 0.2`. And that we should focus on something self-contained that works. I don’t think it should be released before it survives some serious comparison with the equivalent implementations in `sklearn` and `R` on simulated and real data

**Comment by jasmainak** [comment]
> I don’t think it should be released before it survives some serious comparison with the equivalent implementations in sklearn and R on simulated and real data

I totally agree. We can create a `notebook` for the benchmark. It doesn't have to live in the repo but could be linked via the documentation. Let's just benchmark with `scikit-learn` for now since it's in python and therefore easier to compare if set the same seeds etc.? Maybe we can focus just on the convergence for now and forget about `memory` and/or `timing`? Getting the right result is probably most important :)

**Comment by jasmainak** [comment]
also with regards to the release, I seem to remember that 3 months is a pretty good development cycle adhering to the "release early, release fast" philosophy. 1 month is really fast :)

**Comment by pavanramkumar** [comment]
closely follow [`ElasticNetCV`](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNetCV.html)
