### ISSUE TITLE
make sure np.random.seed can be set in one place globally

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#62]
right now, it needs to be set within `.fit()`

**Comment by jasmainak** [comment]
I added this to `version 0.1` milestone as it seems critical to reproducibility of our results. We can add an argument to `GLM` called `random_state` or `seed` which gets used by all the methods in GLM. What do you think?

**Comment by daniel-acuna** [comment]
Yeah, lets add random state to GLM

**Comment by daniel-acuna** [comment]
![image](https://cloud.githubusercontent.com/assets/842569/15227347/5fed7dca-184c-11e6-8110-649b92007b14.png)

**Comment by daniel-acuna** [comment]
@pavanramkumar I can't fix it without knowing first the reasoning behind it. 

It seems that it is used for ensuring reproducibility but I don't know where and therefore making it a parameter of GLM may not fix the problem since the seed setting is also [here](https://github.com/pavanramkumar/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L9), which is really strange

**Comment by pavanramkumar** [comment]
@daniel-acuna setting it [outside](https://github.com/pavanramkumar/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L9) the class alone was not sufficient to produce reproducible results. that's why I had to set it [inside](https://github.com/pavanramkumar/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L9) the fit function as well. i thought if we accept `RandomState` as a parameter, it can be used to set the seed within each function that uses `np.random`
