### ISSUE TITLE
move `simulate` out of `GLM` class

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#96]
@pavanramkumar isn't it a bit counterintuitive that you would need to instantiate a `GLM` object to simulate it? I think we should move the `simulate` method outside the `GLM` class.

**Comment by pavanramkumar** [comment]
@jasmainak 

`simulate()` calls `self.lmb()` which in turn calls `self.qu()`. also it has the attractive property that once the user instantiates an object, they can not only fit data with it but also simulate without having the specify the `distr` again.

**Comment by pavanramkumar** [comment]
@jasmainak do you agree? if so, we can close this issue

**Comment by jasmainak** [comment]
@pavanramkumar the methods can be factored out of the class. I think this would also solve the problems you are having in the PR #84 . If you really need the object, you can ask the user to pass it as an argument to the function but I still think it's a bit weird to require your model for simulation. Maybe we can take some inspiration from [`scikit-learn` samples generators](http://scikit-learn.org/stable/modules/classes.html#samples-generator) or [`mne-python` simulation module](https://github.com/mne-tools/mne-python/tree/master/examples/simulation) to see what's the best way to do it.

**Comment by pavanramkumar** [comment]
@jasmainak i like the samples generators approach used by `scikit-learn` but still feel it's for a different purpose. Let me make my case!

- The `datasets` methods are good to simulate an entire dataset, i.e. both `X` and `y`. By contrast, our `simulate` function takes `X` and `beta` as inputs and simulates `y`. This is often useful when we want to simulate a corner-case and test if our estimator can fit those specific rare scenarios. It's also useful to re-generate test samples from our fit model, so that we can use those samples in non-parametric statistical tests, etc.

- Especially now, since `__qu()` and `__lmb()` are private methods, `simulate()` is super convenient the way it is written and produces target variables for each type of distribution with any additional helper functions that we would otherwise need to duplicate.

- Creating a new set of simulation methods will add extra documentation and make the learning curve steeper.

- Finally, remember we have the freedom to not conform to `scikit-learn` conventions if our conventions are better :-)

**Comment by jasmainak** [comment]
@pavanramkumar okay, let's keep it how it is for now :) I definitely agree we don't need to conform to `scikit-learn` conventions if we can come up with better conventions !

**Comment by jasmainak** [comment]
closing this issue for now
