### ISSUE TITLE
make `GLM` object compatible with `Pipeline` object

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#98]
```py
from sklearn.pipeline import Pipeline
from sklearn import cross_val_score
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
glm = GLM()
clf = Pipeline([("scaler", scaler), ("glm", glm)])
score = cross_val_score(X, y)
```
Not sure if it's already compatible. We should check. Maybe we could change the test `test_cv` into `test_sklearn_compatibility`?

**Comment by daniel-acuna** [comment]
I can work on this

**Comment by daniel-acuna** [comment]
Please see https://github.com/pavanramkumar/pyglmnet/pull/126 for an attempt at solving this issue

**Comment by pavanramkumar** [comment]
after the pydata conference, i've come to appreciate the power of pipelines a lot more! 

i had a simple idea to make `score()` compatible with pipelines easily: 
- create an extra instance variable `ynull` that stores `np.mean(ytrain)`.
- implement this in the `fit()` method.
- write a simple test to make sure that `score()` cannot be called `if self.ynull is not None`.

**Comment by jasmainak** [comment]
yeah, that sounds like a neat idea indeed. Maybe call it `ynull_` since it's something you estimate. And we can use `hasattr` to check if the attribute exists

**Comment by pavanramkumar** [comment]
I briefly reviewed these two stalled PRs #124 and #126. Pipeline compatibility is holding up both of them:

- if we accept PR #124 then we get a score for all values of `reg_lamba` when we call `glm.score()` without slicing. this is not compatible with pipelines because `cross_val_score` expects a scalar from the estimator's score function.

- PR #126 currently doesn't make sense -- it averages the score across all lambdas.

My suggestion is to abandon these PRs and submit a new PR which combines both by implementing `score()` to 
- return a vector if the estimator is not sliced and a scalar otherwise (goal of #PR 124)
- be reparameterized with `Xtest`, `ytest`, call self.predict() from within for `ytest_hat`, and use the idea of the stored `ynull_` attribute from `fit()`
- test and raise an issue if `fit()` has not yet been called on the estimator
- insert a note in `score()`'s docstring that only a sliced object will be compatible with pipelines

This will break all the tests and examples calling `score()` so the PR should also check for these and make appropriate changes everywhere.

**Comment by jasmainak** [comment]
@pavanramkumar that sounds like a great plan to me. We should definitely go ahead with this PR. If we have compatibility with the `Pipeline` object, we can already advertise the fact that you can work with `pyglmnet` and use advanced grid search / pipeline / cv objects from `scikit-learn` at the same time. Taken together with the fact that you can do all this in R style, that is predict and score for all lambdas, I think we already have many selling points for the first release. We should make sure that the implementation has no major bugs and maybe pick some other low lying fruits. 

For the future, we should definitely think about:
1. Automatic differentiation using theano etc.
2. Demo this on real datasets (maybe have dataset fetchers? I don't know ...)
But I feel we should let some of these ideas ferment a bit. More features mean more bugs and more code complexity. And we don't have too many developers working on it actively (yet ...)

**Comment by pavanramkumar** [comment]
Awesome. I'll take this up as soon as I finish and merge #142

**Comment by pavanramkumar** [comment]
It appears that each estimator or classifier in `scikit-learn` comes with a `score` function which only accepts `Xtest` and `ytest`. This means I cannot call `score()` with `method='deviance'` or `method='pseudo_R2'`.

One workaround to make `GLM.score()` compatible with pipelines is to have a parameter at initialization called `scorer` which can be set to `deviance` or `pseudo_R2`. This can then be used by `GLM.score()`. I'm happy with this but can we do better?

@jasmainak you know `BaseEstimator` best. Can an estimator or classifier have more than one user-specifiable score?

**Comment by jasmainak** [comment]
@pavanramkumar you can have additional arguments to `score` of course. Do you mean you want to be able to use both methods for cross-validation and grid search? I think in that case, we should probably have a file called `metrics.py` which has these two scoring functions:

```py
from pyglmnet.metrics import deviance
from sklearn.metrics import make_scorer
deviance_scorer = make_scorer(deviance)
grid = GridSearchCV(glm, lambdas={'l: [1, 10]}, scoring=deviance_scorer)
```

and the `score` method for `GLM.score()` by default could be either `deviance` or `pseudo_R2` whatever you like.

**Comment by pavanramkumar** [comment]
i wrote it like this, so `GridSearchCV` can use `scoring=None`:

```python
glm = GLM(..., scorer='deviance')
glm.score(Xtest, ytest)
```

**Comment by jasmainak** [comment]
okay, sounds good to me. Only thing, I would be more explicit and call it `scoring_method` instead of `scorer`
